package com.example.lifeafterdorm.controller

val countryCodes = mapOf(
    "Afghanistan" to "+93",
    "Albania" to "+355",
    "Algeria" to "+213",
    "American Samoa" to "+1-684",
    "Andorra" to "+376",
    "Angola" to "+244",
    "Anguilla" to "+1-264",
    "Antigua and Barbuda" to "+1-268",
    "Argentina" to "+54",
    "Armenia" to "+374",
    "Aruba" to "+297",
    "Australia" to "+61",
    "Austria" to "+43",
    "Azerbaijan" to "+994",
    "Bahrain" to "+973",
    "Bangladesh" to "+880",
    "Barbados" to "+1-246",
    "Belarus" to "+375",
    "Belgium" to "+32",
    "Belize" to "+501",
    "Benin" to "+229",
    "Bermuda" to "+1-441",
    "Bhutan" to "+975",
    "Bolivia" to "+591",
    "Bosnia and Herzegovina" to "+387",
    "Botswana" to "+267",
    "Brazil" to "+55",
    "British Indian Ocean Territory" to "+246",
    "British Virgin Islands" to "+1-284",
    "Brunei" to "+673",
    "Bulgaria" to "+359",
    "Burkina Faso" to "+226",
    "Burundi" to "+257",
    "Cambodia" to "+855",
    "Cameroon" to "+237",
    "Canada" to "+1",
    "Cape Verde" to "+238",
    "Cayman Islands" to "+1-345",
    "Central African Republic" to "+236",
    "Chad" to "+235",
    "Chile" to "+56",
    "China" to "+86",
    "Christmas Island" to "+61",
    "Cocos (Keeling) Islands" to "+61",
    "Colombia" to "+57",
    "Comoros" to "+269",
    "Congo" to "+242",
    "Cook Islands" to "+682",
    "Costa Rica" to "+506",
    "Cote d'Ivoire" to "+225",
    "Croatia" to "+385",
    "Cuba" to "+53",
    "Cyprus" to "+357",
    "Czech Republic" to "+420",
    "Democratic Republic of the Congo" to "+243",
    "Denmark" to "+45",
    "Djibouti" to "+253",
    "Dominica" to "+1-767",
    "Dominican Republic" to "+1-809, +1-829, +1-849",
    "East Timor" to "+670",
    "Ecuador" to "+593",
    "Egypt" to "+20",
    "El Salvador" to "+503",
    "Equatorial Guinea" to "+240",
    "Eritrea" to "+291",
    "Estonia" to "+372",
    "Ethiopia" to "+251",
    "Faeroe Islands" to "+298",
    "Falkland Islands" to "+500",
    "Fiji" to "+679",
    "Finland" to "+358",
    "France" to "+33",
    "French Guiana" to "+594",
    "French Polynesia" to "+689",
    "Gabon" to "+241",
    "Georgia" to "+995",
    "Germany" to "+49",
    "Ghana" to "+233",
    "Gibraltar" to "+350",
    "Greece" to "+30",
    "Greenland" to "+299",
    "Grenada" to "+1-473",
    "Guadeloupe" to "+590",
    "Guam" to "+1-671",
    "Guatemala" to "+502",
    "Guinea" to "+224",
    "Guinea-Bissau" to "+245",
    "Guyana" to "+592",
    "Haiti" to "+509",
    "Honduras" to "+504",
    "Hong Kong" to "+852",
    "Hungary" to "+36",
    "Iceland" to "+354",
    "India" to "+91",
    "Indonesia" to "+62",
    "Iran" to "+98",
    "Iraq" to "+964",
    "Ireland" to "+353",
    "Israel" to "+972",
    "Italy" to "+39",
    "Jamaica" to "+1-876",
    "Japan" to "+81",
    "Jordan" to "+962",
    "Kazakhstan" to "+7",
    "Kenya" to "+254",
    "Kiribati" to "+686",
    "Kuwait" to "+965",
    "Kyrgyzstan" to "+996",
    "Laos" to "+856",
    "Latvia" to "+371",
    "Lebanon" to "+961",
    "Lesotho" to "+266",
    "Liberia" to "+231",
    "Libya" to "+218",
    "Liechtenstein" to "+423",
    "Lithuania" to "+370",
    "Luxembourg" to "+352",
    "Macau" to "+853",
    "Madagascar" to "+261",
    "Malawi" to "+265",
    "Malaysia" to "+60",
    "Maldives" to "+960",
    "Mali" to "+223",
    "Malta" to "+356",
    "Marshall Islands" to "+692",
    "Martinique" to "+596",
    "Mauritania" to "+222",
    "Mauritius" to "+230",
    "Mayotte" to "+262",
    "Mexico" to "+52",
    "Micronesia" to "+691",
    "Moldova" to "+373",
    "Monaco" to "+377",
    "Mongolia" to "+976",
    "Montenegro" to "+382",
    "Montserrat" to "+1-664",
    "Morocco" to "+212",
    "Mozambique" to "+258",
    "Myanmar" to "+95",
    "Namibia" to "+264",
    "Nauru" to "+674",
    "Nepal" to "+977",
    "Netherlands" to "+31",
    "New Caledonia" to "+687",
    "New Zealand" to "+64",
    "Nicaragua" to "+505",
    "Niger" to "+227",
    "Nigeria" to "+234",
    "Niue" to "+683",
    "Norfolk Island" to "+672",
    "North Korea" to "+850",
    "Northern Marianas" to "+1-670",
    "Norway" to "+47",
    "Oman" to "+968",
    "Pakistan" to "+92",
    "Palau" to "+680",
    "Panama" to "+507",
    "Papua New Guinea" to "+675",
    "Paraguay" to "+595",
    "Peru" to "+51",
    "Philippines" to "+63",
    "Pitcairn Islands" to "+64",
    "Poland" to "+48",
    "Portugal" to "+351",
    "Puerto Rico" to "+1-787, +1-939",
    "Qatar" to "+974",
    "Reunion" to "+262",
    "Romania" to "+40",
    "Russia" to "+7",
    "Rwanda" to "+250",
    "Sqo Tome and Principe" to "+239",
    "Saint Helena" to "+290",
    "Saint Kitts and Nevis" to "+1-869",
    "Saint Lucia" to "+1-758",
    "Saint Pierre and Miquelon" to "+508",
    "Saint Vincent and the Grenadines" to "+1-784",
    "Samoa" to "+685",
    "San Marino" to "+378",
    "Saudi Arabia" to "+966",
    "Senegal" to "+221",
    "Serbia" to "+381",
    "Seychelles" to "+248",
    "Sierra Leone" to "+232",
    "Singapore" to "+65",
    "Slovakia" to "+421",
    "Slovenia" to "+386",
    "Solomon Islands" to "+677",
    "Somalia" to "+252",
    "South Africa" to "+27",
    "South Georgia and the South Sandwich Islands" to "+500",
    "South Korea" to "+82",
    "South Sudan" to "+211",
    "Spain" to "+34",
    "Sri Lanka" to "+94",
    "Sudan" to "+249",
    "Suriname" to "+597",
    "Svalbard and Jan Mayen" to "+47",
    "Swaziland" to "+268",
    "Sweden" to "+46",
    "Switzerland" to "+41",
    "Syria" to "+963",
    "Taiwan" to "+886",
    "Tajikistan" to "+992",
    "Tanzania" to "+255",
    "Thailand" to "+66",
    "The Bahamas" to "+1-242",
    "The Gambia" to "+220",
    "Togo" to "+228",
    "Tokelau" to "+690",
    "Tonga" to "+676",
    "Trinidad and Tobago" to "+1-868",
    "Tunisia" to "+216",
    "Turkey" to "+90",
    "Turkmenistan" to "+993",
    "Turks and Caicos Islands" to "+1-649",
    "Tuvalu" to "+688",
    "Uganda" to "+256",
    "Ukraine" to "+380",
    "United Arab Emirates" to "+971",
    "United Kingdom" to "+44",
    "United States" to "+1",
    "Uruguay" to "+598",
    "Uzbekistan" to "+998",
    "Vanuatu" to "+678",
    "Vatican City" to "+39",
    "Venezuela" to "+58",
    "Vietnam" to "+84",
    "Wallis and Futuna" to "+681",
    "Western Sahara" to "+212",
    "Yemen" to "+967",
    "Zambia" to "+260",
    "Zimbabwe" to "+263"
)

fun getCountryCode(selectedCountry: String): String {
    return countryCodes[selectedCountry] ?: "N/A"
}

fun isValidPhoneNumber(phoneNumber: String): Boolean {
    val phonePattern = "^[0-9]{7,15}\$"
    return phoneNumber.matches(phonePattern.toRegex())
}

fun separateCountryCodeAndNumber(combinedString: String): Pair<String, String>? {
    for ((country, code) in countryCodes) {
        if (combinedString.startsWith(code)) {
            val countryCode = code
            val phoneNumber = combinedString.substring(code.length)
            return Pair(countryCode, phoneNumber)
        }
    }
    return null
}

